=== agaraycanas/edutrack/legacy/programaciones/dat/programaciones.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT programacion (departamento*)>

<!ELEMENT departamento (curso*)>
	<!ATTLIST departamento
		nombre CDATA #REQUIRED
	>

	<!ELEMENT curso (asignatura*)>
		<!ATTLIST curso
			nombre CDATA #REQUIRED
		>
	
		<!ELEMENT asignatura (grupo*,tema*)>
			<!ATTLIST asignatura
				nombre CDATA #REQUIRED
			>
			
			<!ELEMENT grupo (#PCDATA)>
				<!ATTLIST grupo
					id CDATA #REQUIRED
					profe CDATA #REQUIRED
					nif CDATA #REQUIRED
					inicio CDATA #REQUIRED
					fin CDATA #REQUIRED
					Mon CDATA #REQUIRED
					Tue CDATA #REQUIRED
					Wed CDATA #REQUIRED
					Thu CDATA #REQUIRED
					Fri CDATA #REQUIRED
				>
		
			<!ELEMENT tema (#PCDATA)>
				<!ATTLIST tema
					n CDATA #REQUIRED
					titulo CDATA #REQUIRED
					horas CDATA #REQUIRED
				>

=== agaraycanas/edutrack/legacy/programaciones/dat/programaciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE programacion SYSTEM "programaciones.dtd">

<programacion>

<departamento nombre="Informática">

<curso nombre="DAM1d">
<asignatura nombre="Bases de datos"><grupo id="m1d" profe="Marcos" nif="Marcos" inicio="25-9-12" fin="26-4-10" Mon="1" Tue="2" Wed="1" Thu="0" Fri="2" /><tema n="1" titulo="Sistemas de almacenamiento de datos" horas="6" /><tema n="2" titulo="Procesos de diseño de bases de datos" horas="24" /><tema n="3" titulo="Bases de datos relacionales. Normalización" horas="16" /><tema n="4" titulo="Lenguaje de descripción de datos. DDL" horas="24" /><tema n="5" titulo="Lenguaje de manipulación de datos. DML" horas="34" /><tema n="6" titulo="Lenguaje de control de datos (DCL) y optimización" horas="12" /><tema n="7" titulo="Programación en bases de datos relacionales" horas="32" /><tema n="8" titulo="Bases de datos no relacionales" horas="12" /></asignatura>
<asignatura nombre="Entornos de desarrollo"><grupo id="m1d" profe="MJose" nif="MJose" inicio="25-9-12" fin="26-4-10" Mon="0" Tue="1" Wed="1" Thu="0" Fri="0" /><tema n="1" titulo="Desarrollo de software (RA1)" horas="6" /><tema n="2" titulo="Instalación y uso de entornos de desarrollo (RA2)" horas="2" /><tema n="3" titulo="Optimización y documentación (RA4)" horas="8" /><tema n="4" titulo="Diagramas de clases (RA5)" horas="14" /><tema n="5" titulo="Diagramas de comportamiento (RA6)" horas="12" /><tema n="6" titulo="Diseño y realización de pruebas (RA3)" horas="8" /><tema n="7" titulo="FFE" horas="12" /></asignatura>
<asignatura nombre="Fundamentos de la Programación"><grupo id="m1d" profe="Elena" nif="Elena" inicio="25-9-12" fin="26-4-10" Mon="2" Tue="0" Wed="0" Thu="0" Fri="0" /><tema n="1" titulo="Introducción a la programación y al entorno" horas="4" /><tema n="2" titulo="Introducción a PSeInt" horas="2" /><tema n="3" titulo="Elementos de un programa informático" horas="2" /><tema n="4" titulo="Estructuras de control" horas="4" /><tema n="5" titulo="Estructuras de datos (datos compuestos)" horas="1" /><tema n="6" titulo="Funciones y librerías" horas="9" /><tema n="7" titulo="POO" horas="11" /><tema n="8" titulo="Excepciones y fichero" horas="3" /><tema n="9" titulo="BBDD" horas="6" /></asignatura>
<asignatura nombre="Lenguajes de marcas"><grupo id="m1d" profe="MJose" nif="MJose" inicio="25-9-12" fin="26-4-10" Mon="1" Tue="0" Wed="0" Thu="0" Fri="2" /><tema n="1" titulo="Reconocimiento de las características de lenguajes de marcas" horas="3" /><tema n="2" titulo="Lenguajes para la visualización de información" horas="3" /><tema n="3" titulo="HTML" horas="12" /><tema n="4" titulo="CSS" horas="12" /><tema n="5" titulo="Lenguajes para el almacenamiento y transmisión de información" horas="4" /><tema n="6" titulo="Definición de esquemas y vocabularios en XML" horas="15" /><tema n="7" titulo="Conversión y adaptación de documentos XML" horas="14" /><tema n="8" titulo="Almacenamiento de la información" horas="0" /><tema n="9" titulo="Aplicación de los lenguajes de marcas a la sindicación de contenidos" horas="4" /><tema n="10" titulo="Sistemas de gestión empresarial" horas="0" /><tema n="11" titulo="FFE" horas="12" /></asignatura>
<asignatura nombre="Programación"><grupo id="m1d" profe="Ignacio" nif="Ignacio" inicio="25-9-12" fin="26-4-10" Mon="2" Tue="0" Wed="2" Thu="2" Fri="2" /><tema n="1" titulo="Introducción a la programación" horas="6" /><tema n="2" titulo="Tipos de datos. Manejo de la información" horas="18" /><tema n="3" titulo="Estructuras de control de flujo" horas="22" /><tema n="4" titulo="Arrays" horas="29" /><tema n="5" titulo="Colecciones de datos y diccionarios" horas="30" /><tema n="6" titulo="Introducción a POO" horas="16" /><tema n="7" titulo="POO. Herencia e interfaces" horas="16" /><tema n="8" titulo="Comparación y ordenación de objetos" horas="16" /><tema n="9" titulo="Excepciones" horas="6" /><tema n="10" titulo="Sistema de ficheros. Procesamiento de la información" horas="18" /><tema n="11" titulo="Otras cuestiones de interés" horas="6" /><tema n="12" titulo="Interfaces gráficas de usuario (FFE1)" horas="10" /><tema n="13" titulo="CRUD en bases de datos (FFE1)" horas="6" /><tema n="14" titulo="Interfaces gráficas de usuario (FFE2)" horas="10" /><tema n="15" titulo="CRUD en bases de datos (FFE2)" horas="6" /></asignatura>
<asignatura nombre="Sistemas informáticos"><grupo id="m1d" profe="Chema" nif="Chema" inicio="25-9-12" fin="26-4-10" Mon="2" Tue="0" Wed="2" Thu="2" Fri="0" /><tema n="1" titulo="Sistemas informáticos. Representación de la información." horas="12" /><tema n="2" titulo="Funcionamiento Sistemas Informáticos. Máquinas Virtuales" horas="12" /><tema n="3" titulo="Linux y Windows Básico y Sistemas de Ficheros" horas="10" /><tema n="4" titulo="Sistemas de Almacenamiento en Windows y Linux" horas="20" /><tema n="5" titulo="Administración de Sistemas Operativos Windows y Linux" horas="30" /><tema n="6" titulo="Automatización de Tareas. Scripting en Windows y Linux" horas="24" /><tema n="7" titulo="Sistemas Operativos en Red" horas="22" /><tema n="8" titulo="Configuración IP de Sistemas Informáticos" horas="10" /><tema n="9" titulo="Redes IP " horas="10" /></asignatura>
</curso>

<curso nombre="DAM1v">
<asignatura nombre="Bases de datos"><grupo id="m1v" profe="Vicente" nif="Vicente" inicio="25-9-12" fin="26-4-10" Mon="0" Tue="2" Wed="2" Thu="0" Fri="2" /><tema n="1" titulo="Sistemas de almacenamiento de datos" horas="6" /><tema n="2" titulo="Procesos de diseño de bases de datos" horas="32" /><tema n="3" titulo="Bases de datos relacionales. Normalización" horas="35" /><tema n="4" titulo="Lenguaje de descripción de datos. DDL" horas="24" /><tema n="5" titulo="Lenguaje de manipulación de datos. DML" horas="42" /><tema n="6" titulo="Lenguaje de control de datos (DCL) y optimización" horas="12" /><tema n="7" titulo="Programación en bases de datos relacionales (FFE I)" horas="21" /><tema n="8" titulo="Programación en bases de datos relacionales (FFE II)" horas="21" /><tema n="9" titulo="Bases de datos no relacionales" horas="12" /></asignatura>
<asignatura nombre="Entornos de desarrollo"><grupo id="m1v" profe="Vicente" nif="Vicente" inicio="25-9-12" fin="26-4-10" Mon="1" Tue="0" Wed="0" Thu="0" Fri="1" /><tema n="1" titulo="Desarrollo de software (RA1)" horas="4" /><tema n="2" titulo="Instalación y uso de entornos de desarrollo (RA2)" horas="2" /><tema n="3" titulo="Optimización y documentación (RA4)" horas="6" /><tema n="4" titulo="Diagramas de clases (RA5)" horas="16" /><tema n="5" titulo="Diagramas de comportamiento (RA6)" horas="16" /><tema n="6" titulo="Diseño y realización de pruebas (RA3) (FFE I)" horas="8" /><tema n="7" titulo="Diseño y realización de pruebas (RA3) (FFE II)" horas="8" /></asignatura>
<asignatura nombre="Fundamentos de la Programación"><grupo id="m1v" profe="Ps3v" nif="Ps3v" inicio="25-9-12" fin="26-4-10" Mon="2" Tue="0" Wed="0" Thu="0" Fri="0" /><tema n="1" titulo="Introducción a la programación" horas="2" /><tema n="2" titulo="Elementos de un programa informático" horas="6" /><tema n="3" titulo="Estructuras de control" horas="6" /><tema n="4" titulo="Estructuras de datos (datos compuestos)" horas="8" /><tema n="5" titulo="Funciones y librerías" horas="8" /><tema n="6" titulo="Excepciones y manejo de errores" horas="4" /><tema n="7" titulo="Estructuras externas: ficheros y bases de datos (FFE 1)" horas="4" /><tema n="8" titulo="Estructuras externas: ficheros y bases de datos (FFE2)" horas="4" /><tema n="9" titulo="Introducción a la POO (FFE 1)" horas="4" /><tema n="10" titulo="Introducción a la POO (FFE 2)" horas="4" /></asignatura>
<asignatura nombre="Lenguajes de marcas"><grupo id="m1v" profe="Vicente" nif="Vicente" inicio="25-9-12" fin="26-4-10" Mon="1" Tue="1" Wed="0" Thu="1" Fri="0" /><tema n="1" titulo="Reconocimiento de las características de lenguajes de marcas" horas="5" /><tema n="2" titulo="Lenguajes para la visualización de información" horas="29" /><tema n="3" titulo="Lenguajes para el almacenamiento y transmisión de información" horas="15" /><tema n="4" titulo="Definición de esquemas y vocabularios en XML" horas="15" /><tema n="5" titulo="Almacenamiento de información" horas="15" /><tema n="6" titulo="Conversión y adaptación de documentos XML (FFE I)" horas="12" /><tema n="7" titulo="Conversión y adaptación de documentos XML (FFE II)" horas="12" /><tema n="8" titulo="Aplicación de los lenguajes de marcas a la sindicación de contenidos" horas="4" /><tema n="9" titulo="Sistemas de gestión empresarial" horas="3" /></asignatura>
<asignatura nombre="Programación"><grupo id="m1v" profe="Ps3v" nif="Ps3v" inicio="25-9-12" fin="26-4-10" Mon="2" Tue="2" Wed="0" Thu="2" Fri="2" /><tema n="1" titulo="Introducción a la programación" horas="8" /><tema n="2" titulo="Tipos de datos. Manejo de la información" horas="22" /><tema n="3" titulo="Estructuras de control de flujo" horas="28" /><tema n="4" titulo="Arrays" horas="36" /><tema n="5" titulo="Colecciones de datos y diccionarios" horas="38" /><tema n="6" titulo="Introducción a POO" horas="20" /><tema n="7" titulo="POO. Herencia e interfaces" horas="20" /><tema n="8" titulo="Comparación y ordenación de objetos" horas="20" /><tema n="9" titulo="Excepciones" horas="8" /><tema n="10" titulo="Sistema de ficheros. Procesamiento de la información" horas="22" /><tema n="11" titulo="Otras cuestiones de interés" horas="8" /><tema n="12" titulo="Interfaces gráficas de usuario (FFE1)" horas="12" /><tema n="13" titulo="CRUD en bases de datos (FFE1)" horas="8" /><tema n="14" titulo="Interfaces gráficas de usuario (FFE2)" horas="12" /><tema n="15" titulo="CRUD en bases de datos (FFE2)" horas="8" /></asignatura>
