=== agaraycanas/edutrack/legacy/programaciones/dat/seguimiento.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT seguimiento (asignatura*)>

<!ELEMENT asignatura (tema*)>
	<!ATTLIST asignatura
		nombre CDATA #REQUIRED
		grupo CDATA #REQUIRED
	>			
	
	<!ELEMENT tema (#PCDATA)>
		<!ATTLIST tema
			n CDATA #REQUIRED
			fini CDATA #REQUIRED
			ffin CDATA #REQUIRED
                        comentario CDATA #REQUIRED
		>

=== agaraycanas/edutrack/legacy/programaciones/dat/seguimiento-Alberto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seguimiento SYSTEM "seguimiento.dtd">
<seguimiento>
    <asignatura grupo="w1" nombre="Programación">
        <tema n="1" fini="2025-9-29" ffin="2025-10-3" comentario=""/>
        <tema n="2" fini="2025-10-6" ffin="2025-10-17" comentario=""/>
        <tema n="3" fini="2025-10-20" ffin="2025-11-4" comentario=""/>
        <tema n="4" fini="2025-11-5" ffin="2025-11-18" comentario=""/>
        <tema n="5" fini="2026-1-29" ffin="2026-2-9" comentario=""/>
        <tema n="6" fini="2025-11-19" ffin="2025-12-18" comentario=""/>
        <tema n="7" fini="2025-12-19" ffin="2026-1-28" comentario=""/>
        <tema n="8" fini="2026-2-10" ffin="2026-2-17" comentario=""/>
        <tema n="9" fini="2026-2-18" ffin="" comentario=""/>
        <tema n="10" fini="" ffin="" comentario=""/>
        <tema n="11" fini="" ffin="" comentario=""/>
        <tema n="12" fini="" ffin="" comentario=""/>
        <tema n="13" fini="" ffin="" comentario=""/>
        <tema n="14" fini="" ffin="" comentario=""/>
        <tema n="15" fini="" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="w2" nombre="Desarrollo de aplicaciones web en entorno servidor">
        <tema n="1" fini="2025-9-29" ffin="2025-10-9" comentario=""/>
        <tema n="2" fini="2025-10-10" ffin="2025-10-20" comentario=""/>
        <tema n="3" fini="2025-10-21" ffin="2025-11-6" comentario=""/>
        <tema n="4" fini="2025-11-7" ffin="2025-11-14" comentario=""/>
        <tema n="5" fini="2025-11-17" ffin="2025-12-2" comentario=""/>
        <tema n="6" fini="2025-12-5" ffin="2025-12-19" comentario=""/>
        <tema n="7" fini="2026-1-9" ffin="2026-1-15" comentario=""/>
        <tema n="8" fini="2026-1-16" ffin="2026-1-30" comentario=""/>
        <tema n="9" fini="2026-2-16" ffin="2026-2-17" comentario=""/>
        <tema n="10" fini="2026-2-23" ffin="" comentario=""/>
    </asignatura>
</seguimiento>

=== agaraycanas/edutrack/legacy/programaciones/dat/seguimiento-Sergio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seguimiento SYSTEM "seguimiento.dtd">
<seguimiento>
    <asignatura grupo="s1b" nombre="Aplicaciones ofimáticas">
        <tema n="1" fini="2025-9-12" ffin="2025-9-19" comentario=""/>
        <tema n="2" fini="2025-9-22" ffin="2025-10-24" comentario="Retrasos derivados de huelgas, otras causas externas y el propio grupo que ha avanzado más lento de lo esperado ha provocado un retraso en la fecha estimada"/>
        <tema n="3" fini="2025-10-27" ffin="2025-12-5" comentario="Retrasos por falta de ritmo del grupo"/>
        <tema n="4" fini="2025-12-5" ffin="2025-12-12" comentario=""/>
        <tema n="5" fini="2025-12-12" ffin="2025-12-19" comentario=""/>
        <tema n="6" fini="2026-1-9" ffin="2026-2-13" comentario=""/>
        <tema n="7" fini="2026-2-13" ffin="2026-2-23" comentario=""/>
        <tema n="8" fini="2026-2-24" ffin="2026-3-13" comentario=""/>
        <tema n="9" fini="2026-3-13" ffin="2026-4-15" comentario=""/>
        <tema n="10" fini="" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="s1b" nombre="Fundamentos de las Bases de datos">
        <tema n="1" fini="2025-9-12" ffin="2025-9-26" comentario=""/>
        <tema n="2" fini="2025-10-1" ffin="2025-10-17" comentario=""/>
        <tema n="3" fini="2025-10-22" ffin="2025-11-28" comentario=""/>
        <tema n="4" fini="2025-12-3" ffin="2025-12-19" comentario=""/>
        <tema n="5" fini="2026-1-9" ffin="2026-2-11" comentario=""/>
        <tema n="6" fini="2026-2-13" ffin="2026-4-15" comentario=""/>
    </asignatura>
    <asignatura grupo="s1a" nombre="Aplicaciones ofimáticas">
        <tema n="1" fini="2025-9-12" ffin="2025-9-19" comentario=""/>
        <tema n="2" fini="2025-9-22" ffin="2025-10-24" comentario="Retrasos derivados de huelgas, otras causas externas y el propio grupo que ha avanzado más lento de lo esperado ha provocado un retraso en la fecha estimada"/>
        <tema n="3" fini="2025-10-27" ffin="2025-12-5" comentario="Retrasos por falta de ritmo del grupo"/>
        <tema n="4" fini="2025-12-5" ffin="2025-12-12" comentario=""/>
        <tema n="5" fini="2025-12-12" ffin="2025-12-19" comentario=""/>
        <tema n="6" fini="2026-1-8" ffin="2026-2-13" comentario=""/>
        <tema n="7" fini="2026-2-13" ffin="2026-2-23" comentario=""/>
        <tema n="8" fini="2026-2-24" ffin="2026-3-13" comentario=""/>
        <tema n="9" fini="2026-3-13" ffin="2026-4-15" comentario=""/>
        <tema n="10" fini="" ffin="" comentario=""/>
    </asignatura>



</seguimiento>

=== agaraycanas/edutrack/legacy/programaciones/dat/seguimiento-Bea.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seguimiento SYSTEM "seguimiento.dtd">
<seguimiento>
    <asignatura grupo="w2" nombre="Despliegue de aplicaciones web">
        <tema n="1" fini="2025-9-30" ffin="2025-10-24" comentario=""/>
        <tema n="2" fini="2025-11-14" ffin="2026-1-12" comentario="Desde el 17/11 al 21/11 estuve de baja por enfermedad"/>
        <tema n="3" fini="2026-1-13" ffin="2026-2-6" comentario=""/>
        <tema n="4" fini="2025-10-28" ffin="2025-11-11" comentario=""/>
        <tema n="5" fini="2026-2-9" ffin="2026-2-20" comentario=""/>
    </asignatura>
    <asignatura grupo="s1a" nombre="Aplicaciones ofimáticas">
        <tema n="1" fini="" ffin="" comentario=""/>
        <tema n="2" fini="" ffin="" comentario=""/>
        <tema n="3" fini="" ffin="" comentario=""/>
        <tema n="4" fini="" ffin="" comentario=""/>
        <tema n="5" fini="" ffin="" comentario=""/>
        <tema n="6" fini="" ffin="" comentario=""/>
        <tema n="7" fini="" ffin="" comentario=""/>
        <tema n="8" fini="" ffin="" comentario=""/>
        <tema n="9" fini="" ffin="" comentario=""/>
        <tema n="10" fini="" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="s1a" nombre="Redes locales">
        <tema n="1" fini="2025-9-29" ffin="2025-10-8" comentario=""/>
        <tema n="2" fini="2025-10-9" ffin="2025-10-15" comentario=""/>
        <tema n="3" fini="2025-10-16" ffin="2025-10-23" comentario=""/>
        <tema n="4" fini="2025-10-27" ffin="2025-10-31" comentario=""/>
        <tema n="5" fini="2025-11-3" ffin="2025-11-14" comentario="Desde el 17/11 al 21/11 estuve de baja por enfermedad"/>
        <tema n="6" fini="2025-12-2" ffin="2025-12-18" comentario=""/>
        <tema n="7" fini="2026-1-8" ffin="2026-1-15" comentario=""/>
        <tema n="8" fini="2026-1-19" ffin="2026-1-27" comentario=""/>
        <tema n="9" fini="2025-11-24" ffin="2025-12-1" comentario=""/>
        <tema n="10" fini="2026-2-2" ffin="2026-2-6" comentario=""/>
        <tema n="11" fini="2026-2-9" ffin="2026-2-13" comentario=""/>
        <tema n="12" fini="2026-2-16" ffin="2026-2-20" comentario=""/>
        <tema n="13" fini="2026-2-23" ffin="2026-3-6" comentario=""/>
        <tema n="14" fini="2026-3-9" ffin="2026-3-13" comentario=""/>
        <tema n="15" fini="2026-3-16" ffin="2026-3-20" comentario=""/>
        <tema n="16" fini="2026-3-23" ffin="2026-4-10" comentario=""/>
    </asignatura>
    <asignatura grupo="s1b" nombre="Redes locales">
        <tema n="1" fini="2025-9-29" ffin="2025-10-8" comentario=""/>
        <tema n="2" fini="2025-10-9" ffin="2025-10-15" comentario=""/>
        <tema n="3" fini="2025-10-16" ffin="2025-10-24" comentario=""/>
        <tema n="4" fini="2025-10-27" ffin="2025-10-31" comentario=""/>
        <tema n="5" fini="2025-11-3" ffin="2025-11-14" comentario="Desde el 17/11 al 21/11 estuve de baja por enfermedad"/>
        <tema n="6" fini="2025-12-2" ffin="2025-12-18" comentario=""/>
        <tema n="7" fini="2026-1-8" ffin="2026-1-15" comentario=""/>
        <tema n="8" fini="2026-1-16" ffin="2026-2-24" comentario=""/>
        <tema n="9" fini="2025-11-24" ffin="2025-12-1" comentario=""/>
        <tema n="10" fini="2026-2-2" ffin="2026-2-6" comentario=""/>
        <tema n="11" fini="2026-2-9" ffin="2026-2-13" comentario=""/>
        <tema n="12" fini="2026-2-16" ffin="2026-2-20" comentario=""/>
        <tema n="13" fini="2026-2-23" ffin="2026-3-6" comentario=""/>
        <tema n="14" fini="2026-3-9" ffin="2026-3-13" comentario=""/>
        <tema n="15" fini="2026-3-16" ffin="2026-3-20" comentario=""/>
        <tema n="16" fini="2026-3-23" ffin="2026-4-10" comentario=""/>
    </asignatura>
    <asignatura grupo="s2a" nombre="Seguridad en redes">
        <tema n="1" fini="" ffin="" comentario=""/>
        <tema n="2" fini="" ffin="" comentario=""/>
        <tema n="3" fini="" ffin="" comentario=""/>
        <tema n="4" fini="" ffin="" comentario=""/>
        <tema n="5" fini="" ffin="" comentario=""/>
        <tema n="6" fini="" ffin="" comentario=""/>
        <tema n="7" fini="" ffin="" comentario=""/>
        <tema n="8" fini="" ffin="" comentario=""/>
        <tema n="9" fini="" ffin="" comentario=""/>
        <tema n="10" fini="" ffin="" comentario=""/>
        <tema n="11" fini="" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="s2b" nombre="Seguridad en redes">
        <tema n="1" fini="" ffin="" comentario=""/>
        <tema n="2" fini="" ffin="" comentario=""/>
        <tema n="3" fini="" ffin="" comentario=""/>
        <tema n="4" fini="" ffin="" comentario=""/>
        <tema n="5" fini="" ffin="" comentario=""/>
        <tema n="6" fini="" ffin="" comentario=""/>
        <tema n="7" fini="" ffin="" comentario=""/>
        <tema n="8" fini="" ffin="" comentario=""/>
        <tema n="9" fini="" ffin="" comentario=""/>
        <tema n="10" fini="" ffin="" comentario=""/>
        <tema n="11" fini="" ffin="" comentario=""/>
        <tema n="13" fini="" ffin="" comentario=""/>
        <tema n="14" fini="" ffin="" comentario=""/>
        <tema n="15" fini="" ffin="" comentario=""/>
        <tema n="16" fini="" ffin="" comentario=""/>
        <tema n="17" fini="" ffin="" comentario=""/>
        <tema n="18" fini="" ffin="" comentario=""/>
        <tema n="19" fini="" ffin="" comentario=""/>
        <tema n="20" fini="" ffin="" comentario=""/>
    </asignatura>
</seguimiento>

=== agaraycanas/edutrack/legacy/programaciones/dat/seguimiento-Marcos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seguimiento SYSTEM "seguimiento.dtd">
<seguimiento>
    <asignatura grupo="m1d" nombre="Bases de datos">
        <tema n="1" fini="2025-9-15" ffin="2025-9-17" comentario=""/>
        <tema n="2" fini="2025-9-19" ffin="2025-10-15" comentario=""/>
        <tema n="3" fini="2025-10-17" ffin="2025-11-5" comentario=""/>
        <tema n="4" fini="2025-11-7" ffin="2025-12-1" comentario=""/>
        <tema n="5" fini="2025-12-2" ffin="2026-2-13" comentario=""/>
        <tema n="6" fini="2026-3-25" ffin="2026-4-9" comentario=""/>
        <tema n="7" fini="2026-2-18" ffin="2026-3-24" comentario=""/>
        <tema n="8" fini="2026-4-13" ffin="2026-4-15" comentario=""/>
    </asignatura>
    <asignatura grupo="m2d" nombre="Acceso a datos">
        <tema n="1" fini="2025-9-12" ffin="2025-9-26" comentario=""/>
        <tema n="2" fini="2026-2-23" ffin="2026-2-27" comentario=""/>
        <tema n="3" fini="2025-9-29" ffin="2025-10-10" comentario=""/>
        <tema n="4" fini="2025-10-16" ffin="2025-11-13" comentario=""/>
        <tema n="5" fini="2025-11-14" ffin="2025-12-4" comentario=""/>
        <tema n="6" fini="2025-12-5" ffin="2026-1-23" comentario=""/>
        <tema n="7" fini="2026-2-2" ffin="2026-2-20" comentario=""/>
    </asignatura>
    <asignatura grupo="w1" nombre="Bases de datos">
        <tema n="1" fini="2025-10-15" ffin="2025-10-17" comentario=""/>
        <tema n="2" fini="2025-9-18" ffin="2025-10-16" comentario=""/>
        <tema n="3" fini="2025-10-20" ffin="2025-11-5" comentario=""/>
        <tema n="4" fini="2025-11-6" ffin="2025-12-1" comentario=""/>
        <tema n="5" fini="2025-12-2" ffin="2026-2-12" comentario=""/>
        <tema n="6" fini="2026-3-25" ffin="2026-4-9" comentario=""/>
        <tema n="7" fini="2026-2-18" ffin="2026-3-24" comentario=""/>
        <tema n="8" fini="2026-4-13" ffin="2026-4-15" comentario=""/>
    </asignatura>
</seguimiento>

=== agaraycanas/edutrack/legacy/programaciones/dat/seguimiento-Jorge.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seguimiento SYSTEM "seguimiento.dtd">
<seguimiento>
    <asignatura grupo="i1" nombre="Montaje y mantenimiento de sistemas">
        <tema n="1" fini="2025-9-11" ffin="2025-9-18" comentario=""/>
        <tema n="2" fini="2025-9-18" ffin="2025-9-23" comentario=""/>
        <tema n="3" fini="2025-9-23" ffin="2025-10-10" comentario=""/>
        <tema n="4" fini="2025-10-10" ffin="2025-10-29" comentario=""/>
        <tema n="5" fini="2025-10-29" ffin="2025-11-17" comentario=""/>
        <tema n="6" fini="2025-11-18" ffin="2025-11-28" comentario=""/>
        <tema n="7" fini="2025-12-1" ffin="2026-1-6" comentario=""/>
        <tema n="8" fini="2026-1-6" ffin="2026-1-27" comentario=""/>
        <tema n="9" fini="2026-1-28" ffin="2026-2-16" comentario=""/>
        <tema n="10" fini="2026-2-16" ffin="" comentario=""/>
        <tema n="11" fini="" ffin="" comentario=""/>
        <tema n="12" fini="" ffin="" comentario=""/>
        <tema n="13" fini="" ffin="" comentario=""/>
        <tema n="14" fini="" ffin="" comentario=""/>
        <tema n="15" fini="" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="i2" nombre="Instalación y mantenimiento de redes para transmisión de datos">
        <tema n="1" fini="2025-9-11" ffin="2025-9-24" comentario=""/>
        <tema n="2" fini="2025-9-25" ffin="2025-10-16" comentario=""/>
        <tema n="3" fini="2025-10-25" ffin="2025-11-18" comentario=""/>
        <tema n="4" fini="2025-11-18" ffin="2025-12-10" comentario=""/>
        <tema n="5" fini="2025-12-11" ffin="2026-1-26" comentario=""/>
        <tema n="6" fini="2026-1-28" ffin="2026-2-18" comentario=""/>
        <tema n="7" fini="" ffin="" comentario=""/>
        <tema n="8" fini="" ffin="" comentario=""/>
        <tema n="9" fini="" ffin="" comentario=""/>
    </asignatura>
</seguimiento>

=== agaraycanas/edutrack/legacy/programaciones/dat/seguimiento-Elena.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seguimiento SYSTEM "seguimiento.dtd">
<seguimiento>
    <asignatura grupo="m1d" nombre="Fundamentos de la Programación">
        <tema n="1" fini="2025-9-12" ffin="2025-10-2" comentario=""/>
        <tema n="2" fini="2025-10-2" ffin="2025-10-9" comentario=""/>
        <tema n="3" fini="2025-10-10" ffin="2025-10-16" comentario=""/>
        <tema n="4" fini="2025-10-17" ffin="2025-10-27" comentario=""/>
        <tema n="5" fini="2025-11-17" ffin="2025-11-24" comentario=""/>
        <tema n="6" fini="2025-12-1" ffin="2026-1-30" comentario=""/>
        <tema n="7" fini="2026-2-2" ffin="2026-2-20" comentario=""/>
        <tema n="8" fini="2026-2-23" ffin="2026-3-6" comentario=""/>
        <tema n="9" fini="2026-3-13" ffin="2026-4-3" comentario=""/>
    </asignatura>
    <asignatura grupo="w1" nombre="Fundamentos de la programación">
        <tema n="1" fini="2025-9-12" ffin="2025-9-18" comentario=""/>
        <tema n="2" fini="2025-9-25" ffin="2025-10-2" comentario=""/>
        <tema n="3" fini="2025-10-3" ffin="2025-10-9" comentario=""/>
        <tema n="4" fini="2025-10-10" ffin="2025-10-31" comentario=""/>
        <tema n="5" fini="2025-11-14" ffin="2025-11-21" comentario=""/>
        <tema n="6" fini="2025-11-28" ffin="2026-1-19" comentario=""/>
        <tema n="7" fini="2026-1-26" ffin="2026-2-20" comentario=""/>
        <tema n="8" fini="2026-2-23" ffin="2026-3-6" comentario=""/>
        <tema n="9" fini="2026-3-13" ffin="2026-4-3" comentario=""/>
    </asignatura>
    <asignatura grupo="s2a" nombre="Aplicaciones Web">
        <tema n="1" fini="2025-9-12" ffin="2025-10-1" comentario=""/>
        <tema n="2" fini="2025-10-2" ffin="2025-12-10" comentario=""/>
        <tema n="3" fini="2025-12-12" ffin="2026-1-30" comentario=""/>
        <tema n="4" fini="2026-2-2" ffin="2026-2-27" comentario=""/>
    </asignatura>
    <asignatura grupo="s2a" nombre="Digitalización aplicada a los sectores productivos">
        <tema n="1" fini="2025-9-24" ffin="2025-10-15" comentario=""/>
        <tema n="2" fini="2025-10-22" ffin="2025-11-5" comentario=""/>
        <tema n="3" fini="2025-11-12" ffin="2025-11-26" comentario=""/>
        <tema n="4" fini="2025-12-3" ffin="2026-1-9" comentario=""/>
        <tema n="5" fini="2026-1-12" ffin="2026-2-27" comentario=""/>
    </asignatura>
    <asignatura grupo="s2b" nombre="Aplicaciones Web">
        <tema n="1" fini="2025-9-12" ffin="2025-10-1" comentario=""/>
        <tema n="2" fini="2025-10-2" ffin="2025-12-3" comentario=""/>
        <tema n="3" fini="2025-12-5" ffin="2026-1-29" comentario=""/>
        <tema n="4" fini="2026-1-30" ffin="2026-2-25" comentario=""/>
    </asignatura>
</seguimiento>

=== agaraycanas/edutrack/legacy/programaciones/dat/seguimiento-Guillermo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seguimiento SYSTEM "seguimiento.dtd">
<seguimiento>
    <asignatura grupo="w2" nombre="Diseño de interfaces web">
        <tema n="1" fini="2025-9-16" ffin="2025-9-17" comentario=""/>
        <tema n="2" fini="2025-9-18" ffin="2025-9-23" comentario=""/>
        <tema n="3" fini="2025-9-24" ffin="2025-9-30" comentario=""/>
        <tema n="4" fini="2025-10-1" ffin="2025-10-21" comentario=""/>
        <tema n="5" fini="2025-10-22" ffin="2025-11-18" comentario=""/>
        <tema n="6" fini="2025-11-19" ffin="2025-11-25" comentario=""/>
        <tema n="7" fini="2025-11-26" ffin="2025-12-2" comentario=""/>
        <tema n="8" fini="2025-12-3" ffin="2026-1-27" comentario=""/>
        <tema n="9" fini="" ffin="" comentario=""/>
        <tema n="10" fini="" ffin="" comentario=""/>
    </asignatura>
</seguimiento>

=== agaraycanas/edutrack/legacy/programaciones/dat/seguimiento-Chema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seguimiento SYSTEM "seguimiento.dtd">
<seguimiento>
    <asignatura grupo="m1d" nombre="Sistemas informáticos">
        <tema n="1" fini="2025-9-15" ffin="2025-9-29" comentario=""/>
        <tema n="2" fini="2025-10-1" ffin="2025-10-21" comentario=""/>
        <tema n="3" fini="2025-10-22" ffin="2025-11-5" comentario=""/>
        <tema n="4" fini="2025-11-6" ffin="2025-12-5" comentario=""/>
        <tema n="5" fini="2025-12-9" ffin="2026-1-29" comentario=""/>
        <tema n="6" fini="" ffin="" comentario=""/>
        <tema n="7" fini="" ffin="" comentario=""/>
        <tema n="8" fini="" ffin="" comentario=""/>
        <tema n="9" fini="" ffin="" comentario=""/>
        <tema n="10" fini="" ffin="" comentario=""/>
        <tema n="11" fini="" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="m2d" nombre="Desarrollo de interfaces">
        <tema n="1" fini="2025-9-15" ffin="2025-10-20" comentario=""/>
        <tema n="2" fini="2025-10-21" ffin="2025-11-18" comentario=""/>
        <tema n="3" fini="2025-11-19" ffin="2025-12-18" comentario=""/>
        <tema n="4" fini="2025-12-19" ffin="2026-1-27" comentario=""/>
        <tema n="5" fini="2026-1-29" ffin="" comentario=""/>
        <tema n="6" fini="" ffin="" comentario=""/>
        <tema n="7" fini="" ffin="" comentario=""/>
        <tema n="8" fini="" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="w1" nombre="Sistemas informáticos">
        <tema n="1" fini="2025-9-15" ffin="2025-9-29" comentario=""/>
        <tema n="2" fini="2025-9-30" ffin="2025-10-16" comentario=""/>
        <tema n="3" fini="2025-10-20" ffin="2025-11-5" comentario=""/>
        <tema n="4" fini="2025-11-6" ffin="2025-12-5" comentario=""/>
        <tema n="5" fini="2025-12-9" ffin="2026-1-29" comentario=""/>
        <tema n="6" fini="" ffin="" comentario=""/>
        <tema n="7" fini="" ffin="" comentario=""/>
        <tema n="8" fini="" ffin="" comentario=""/>
        <tema n="9" fini="" ffin="" comentario=""/>
        <tema n="10" fini="" ffin="" comentario=""/>
        <tema n="11" fini="" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="s1a" nombre="Fundamentos de las Bases de datos">
        <tema n="1" fini="2025-9-15" ffin="2025-10-14" comentario=""/>
        <tema n="2" fini="2025-10-21" ffin="2025-11-17" comentario=""/>
        <tema n="3" fini="2025-11-18" ffin="2026-1-14" comentario=""/>
        <tema n="4" fini="2026-1-20" ffin="" comentario=""/>
        <tema n="5" fini="" ffin="" comentario=""/>
        <tema n="6" fini="" ffin="" comentario=""/>
    </asignatura>
</seguimiento>
