=== agaraycanas/edutrack/legacy/programaciones/dat/seguimiento.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT seguimiento (asignatura*)>

<!ELEMENT asignatura (tema*)>
	<!ATTLIST asignatura
		nombre CDATA #REQUIRED
		grupo CDATA #REQUIRED
	>			
	
	<!ELEMENT tema (#PCDATA)>
		<!ATTLIST tema
			n CDATA #REQUIRED
			fini CDATA #REQUIRED
			ffin CDATA #REQUIRED
                        comentario CDATA #REQUIRED
		>

=== agaraycanas/edutrack/legacy/programaciones/dat/seguimiento-Pse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seguimiento SYSTEM "seguimiento.dtd">
<seguimiento>
    <asignatura grupo="s1b" nombre="Montaje y mantenimiento de equipos">
        <tema n="1" fini="2025-9-16" ffin="2025-9-30" comentario=""/>
        <tema n="2" fini="2025-10-2" ffin="2025-10-14" comentario=""/>
        <tema n="3" fini="2025-10-16" ffin="2025-10-28" comentario=""/>
        <tema n="4" fini="2025-10-30" ffin="2025-11-11" comentario=""/>
        <tema n="5" fini="2025-11-13" ffin="2025-11-25" comentario=""/>
        <tema n="6" fini="2025-11-25" ffin="2025-12-2" comentario=""/>
        <tema n="7" fini="2025-12-2" ffin="2025-12-11" comentario=""/>
        <tema n="8" fini="2025-12-11" ffin="2025-12-18" comentario=""/>
        <tema n="9" fini="2026-1-8" ffin="2026-1-20" comentario=""/>
        <tema n="10" fini="2026-1-20" ffin="2026-2-5" comentario=""/>
        <tema n="11" fini="2026-2-5" ffin="2026-2-12" comentario=""/>
        <tema n="12" fini="" ffin="" comentario=""/>
        <tema n="13" fini="" ffin="" comentario=""/>
        <tema n="20" fini="" ffin="" comentario=""/>
    </asignatura>
</seguimiento>

=== agaraycanas/edutrack/legacy/programaciones/dat/seguimiento-Ps3v.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seguimiento SYSTEM "seguimiento.dtd">
<seguimiento>
    <asignatura grupo="m1v" nombre="Fundamentos de la Programación">
        <tema n="1" fini="2025-10-30" ffin="2025-12-4" comentario=""/>
        <tema n="2" fini="2025-11-4" ffin="2025-11-14" comentario=""/>
        <tema n="3" fini="2025-11-25" ffin="2025-12-19" comentario=""/>
        <tema n="4" fini="2026-1-9" ffin="2026-1-30" comentario=""/>
        <tema n="5" fini="2026-1-30" ffin="2026-2-6" comentario=""/>
        <tema n="6" fini="2026-3-10" ffin="2026-3-24" comentario=""/>
        <tema n="7" fini="2026-4-7" ffin="2026-4-10" comentario=""/>
        <tema n="8" fini="" ffin="" comentario=""/>
        <tema n="9" fini="2026-2-10" ffin="2026-3-6" comentario=""/>
        <tema n="10" fini="" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="m1v" nombre="Programación">
        <tema n="1" fini="2025-10-30" ffin="2025-10-31" comentario=""/>
        <tema n="2" fini="2025-11-4" ffin="2025-11-7" comentario=""/>
        <tema n="3" fini="2025-11-10" ffin="2025-11-27" comentario=""/>
        <tema n="4" fini="2025-11-28" ffin="2025-12-18" comentario=""/>
        <tema n="5" fini="2026-1-8" ffin="2026-1-23" comentario=""/>
        <tema n="6" fini="2026-1-26" ffin="2026-2-12" comentario=""/>
        <tema n="7" fini="2026-2-13" ffin="2026-2-23" comentario=""/>
        <tema n="8" fini="2026-2-24" ffin="2026-3-3" comentario=""/>
        <tema n="9" fini="2026-3-4" ffin="2026-3-10" comentario=""/>
        <tema n="10" fini="2026-3-10" ffin="2026-3-17" comentario=""/>
        <tema n="11" fini="2026-3-18" ffin="2026-3-24" comentario=""/>
        <tema n="12" fini="" ffin="" comentario=""/>
        <tema n="13" fini="2026-3-26" ffin="2026-4-10" comentario=""/>
        <tema n="14" fini="2026-4-16" ffin="" comentario=""/>
        <tema n="15" fini="" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="m2v" nombre="Programación de servicios y procesos">
        <tema n="1" fini="2025-10-30" ffin="2025-11-26" comentario=""/>
        <tema n="2" fini="2025-11-27" ffin="2025-12-18" comentario=""/>
        <tema n="3" fini="2026-1-8" ffin="2026-1-29" comentario=""/>
        <tema n="4" fini="2026-2-2" ffin="2026-2-5" comentario=""/>
        <tema n="5" fini="2026-2-9" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="m2v" nombre="Programación en Pyhton">
        <tema n="1" fini="2025-10-31" ffin="2025-10-31" comentario=""/>
        <tema n="2" fini="2025-10-31" ffin="2025-11-7" comentario=""/>
        <tema n="3" fini="2025-11-7" ffin="2025-11-10" comentario=""/>
        <tema n="4" fini="2025-11-14" ffin="2025-12-15" comentario=""/>
        <tema n="5" fini="2026-1-9" ffin="2026-1-30" comentario=""/>
        <tema n="6" fini="2026-1-30" ffin="2026-2-20" comentario=""/>
    </asignatura>
</seguimiento>

=== agaraycanas/edutrack/legacy/programaciones/dat/seguimiento-Antonio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seguimiento SYSTEM "seguimiento.dtd">
<seguimiento>
    <asignatura grupo="m2d" nombre="Programación de móviles y dispositivos multimedia">
        <tema n="1" fini="2025-9-16" ffin="2025-9-18" comentario=""/>
        <tema n="2" fini="2025-9-23" ffin="2025-10-9" comentario=""/>
        <tema n="3" fini="2025-10-14" ffin="2025-11-13" comentario=""/>
        <tema n="4" fini="2025-11-18" ffin="2025-11-27" comentario=""/>
        <tema n="5" fini="2025-12-2" ffin="2025-12-18" comentario=""/>
        <tema n="6" fini="2026-1-8" ffin="2026-1-14" comentario=""/>
        <tema n="7" fini="2026-1-15" ffin="2026-1-21" comentario=""/>
        <tema n="8" fini="" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="m2d" nombre="Programación en Pyhton">
        <tema n="1" fini="2025-9-11" ffin="2025-9-11" comentario=""/>
        <tema n="2" fini="2025-9-17" ffin="2025-9-17" comentario=""/>
        <tema n="3" fini="2025-9-17" ffin="2025-9-18" comentario=""/>
        <tema n="4" fini="2025-9-23" ffin="2025-11-7" comentario=""/>
        <tema n="5" fini="2025-11-7" ffin="2025-12-3" comentario=""/>
        <tema n="6" fini="2025-12-4" ffin="2026-1-15" comentario=""/>
    </asignatura>
    <asignatura grupo="w2" nombre="Programación en Pyhton">
        <tema n="1" fini="2025-9-12" ffin="2025-9-12" comentario=""/>
        <tema n="2" fini="2025-9-12" ffin="2025-9-12" comentario=""/>
        <tema n="3" fini="2025-9-12" ffin="2025-9-26" comentario=""/>
        <tema n="4" fini="2025-10-3" ffin="2025-11-7" comentario=""/>
        <tema n="5" fini="2025-11-14" ffin="2025-12-5" comentario=""/>
        <tema n="6" fini="2025-12-12" ffin="2026-1-16" comentario=""/>
    </asignatura>
    <asignatura grupo="s2a" nombre="Programación en Python">
        <tema n="1" fini="2025-9-15" ffin="2025-9-15" comentario=""/>
        <tema n="2" fini="2025-9-15" ffin="2025-10-6" comentario=""/>
        <tema n="3" fini="2025-10-20" ffin="2025-11-17" comentario=""/>
        <tema n="4" fini="2025-11-24" ffin="2025-12-15" comentario=""/>
        <tema n="5" fini="2026-1-12" ffin="2026-1-26" comentario=""/>
        <tema n="6" fini="2026-2-2" ffin="2026-2-16" comentario=""/>
    </asignatura>
    <asignatura grupo="s2b" nombre="Programación en Python">
        <tema n="1" fini="2025-9-15" ffin="2025-9-17" comentario=""/>
        <tema n="2" fini="2025-9-22" ffin="2025-10-6" comentario=""/>
        <tema n="3" fini="2025-10-20" ffin="2025-11-17" comentario=""/>
        <tema n="4" fini="2025-11-24" ffin="2025-12-17" comentario=""/>
        <tema n="5" fini="2026-1-12" ffin="2026-1-28" comentario=""/>
        <tema n="6" fini="2026-2-2" ffin="2026-2-16" comentario=""/>
    </asignatura>
</seguimiento>

=== agaraycanas/edutrack/legacy/programaciones/dat/seguimiento-Carmelo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seguimiento SYSTEM "seguimiento.dtd">
<seguimiento>
    <asignatura grupo="s2a" nombre="Seguridad en redes">
        <tema n="1" fini="2025-10-1" ffin="2025-10-16" comentario=""/>
        <tema n="2" fini="2025-10-22" ffin="2025-10-23" comentario=""/>
        <tema n="3" fini="2025-10-29" ffin="2025-11-19" comentario=""/>
        <tema n="4" fini="2025-11-26" ffin="2025-12-18" comentario=""/>
        <tema n="5" fini="2026-1-8" ffin="2026-1-15" comentario=""/>
        <tema n="6" fini="2026-1-22" ffin="2026-2-11" comentario=""/>
        <tema n="7" fini="" ffin="" comentario="No ha dado tiempo a impartir esta Unidad por haberme incorporardo tarde al curso"/>
        <tema n="8" fini="" ffin="" comentario=""/>
        <tema n="9" fini="" ffin="" comentario=""/>
        <tema n="10" fini="" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="s2b" nombre="Seguridad en redes">
        <tema n="1" fini="2025-10-1" ffin="2025-10-16" comentario=""/>
        <tema n="2" fini="2025-10-22" ffin="2025-10-23" comentario=""/>
        <tema n="3" fini="2025-10-29" ffin="2025-11-19" comentario=""/>
        <tema n="4" fini="2025-11-26" ffin="2025-12-18" comentario=""/>
        <tema n="5" fini="2026-1-8" ffin="2026-1-15" comentario=""/>
        <tema n="6" fini="2026-1-22" ffin="2026-2-11" comentario=""/>
        <tema n="7" fini="" ffin="" comentario="No ha dado tiempo a impartir esta Unidad por haberme incorporardo tarde al curso"/>
        <tema n="8" fini="" ffin="" comentario=""/>
        <tema n="9" fini="" ffin="" comentario=""/>
        <tema n="10" fini="" ffin="" comentario=""/>
    </asignatura>
</seguimiento>

=== agaraycanas/edutrack/legacy/programaciones/dat/seguimiento-Victor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seguimiento SYSTEM "seguimiento.dtd">
<seguimiento>
    <asignatura grupo="m1v" nombre="Sistemas informáticos">
        <tema n="1" fini="2025-11-10" ffin="2025-11-28" comentario=""/>
        <tema n="2" fini="2025-12-4" ffin="2025-12-19" comentario=""/>
        <tema n="3" fini="2026-1-12" ffin="" comentario=""/>
        <tema n="4" fini="" ffin="" comentario=""/>
        <tema n="5" fini="" ffin="" comentario=""/>
        <tema n="6" fini="" ffin="" comentario=""/>
        <tema n="7" fini="" ffin="" comentario=""/>
        <tema n="8" fini="" ffin="" comentario=""/>
        <tema n="9" fini="" ffin="" comentario=""/>
        <tema n="10" fini="" ffin="" comentario=""/>
        <tema n="11" fini="" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="m2v" nombre="Desarrollo de interfaces">
        <tema n="1" fini="2025-10-20" ffin="2025-11-7" comentario=""/>
        <tema n="2" fini="2025-11-10" ffin="2025-11-21" comentario=""/>
        <tema n="3" fini="2025-11-25" ffin="2025-12-19" comentario=""/>
        <tema n="4" fini="2026-1-8" ffin="2026-1-16" comentario=""/>
        <tema n="5" fini="2026-1-19" ffin="2026-1-23" comentario=""/>
        <tema n="6" fini="" ffin="" comentario=""/>
        <tema n="7" fini="" ffin="" comentario=""/>
        <tema n="8" fini="" ffin="" comentario=""/>
        <tema n="9" fini="" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="m2v" nombre="Digitalización aplicada a los sectores productivos">
        <tema n="1" fini="2025-10-20" ffin="2025-10-31" comentario=""/>
        <tema n="2" fini="2025-11-3" ffin="2025-11-18" comentario=""/>
        <tema n="3" fini="2025-11-25" ffin="2025-12-16" comentario=""/>
        <tema n="4" fini="2026-1-12" ffin="" comentario=""/>
        <tema n="5" fini="" ffin="" comentario=""/>
        <tema n="6" fini="" ffin="" comentario=""/>
    </asignatura>
    <asignatura grupo="m2v" nombre="Sistemas de gestión empresarial">
        <tema n="1" fini="2025-10-20" ffin="2025-11-5" comentario=""/>
        <tema n="2" fini="2025-11-6" ffin="2025-11-21" comentario=""/>
        <tema n="3" fini="2025-11-24" ffin="2025-12-19" comentario=""/>
        <tema n="4" fini="2026-1-12" ffin="" comentario=""/>
        <tema n="5" fini="" ffin="" comentario=""/>
        <tema n="6" fini="" ffin="" comentario=""/>
    </asignatura>
</seguimiento>
